apiVersion: v1
kind: Pod
metadata:
    name: java-pod
    labels:
      name: java-pod
      app: java-app
spec:
    containers:
      - name: javaapp
        image: jaijp/javaapp:latest
        ports:
        - containerPort: 8080