apiVersion: v1
kind: Service
metadata:
  name: java-service
spec:
  selector:
    name: java-pod
    app: java-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort # For Minikube