apiVersion: v1
kind: Secret
metadata:
  name: jenkins-token # Name of the secret
  namespace: default # Or your namespace
  annotations:
    kubernetes.io/service-account.name: jenkins # Associate with the service account
type: kubernetes.io/service-account-token