# .github/workflows/ci-cd.yml
name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      build_command:
        description: 'Command to execute for building the project'
        required: true
        default: 'echo "No build command provided"'
      working_directory:
        description: 'Optional working directory for the build command'
        required: false
        default: '.'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
      if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
      run: mvn clean install -B

      - name: Build and push Docker image
        if: github.ref == 'refs/heads/master' # Only build and push on main branch
        env:
          DOCKER_REGISTRY: docker.io
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
          IMAGE_NAME: ${{ env.DOCKER_USERNAME }}/your-repository-name
        run: |
          docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" $DOCKER_REGISTRY
          docker build -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:latest
          docker logout $DOCKER_REGISTRY
