name: CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Choose the build type'
        required: true
        type: choice
        options:
          - Build Only
          - Build and Test
      java_version:
        description: 'Select Java version'
        required: true
        type: choice
        options:
          - '17'
          - '21'
    
  push:
    branches: [ feature ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
        run: mvn clean install -B

  
      - name: Build and push Docker image
        if: ${{ github.ref == 'refs/heads/master' }}
        env:
          DOCKER_REGISTRY: docker.io
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
          IMAGE_NAME: jaijp/webapp
        run: |
          docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" $DOCKER_REGISTRY
          docker build -t jaijp/webapp:latest .
          docker push jaijp/webapp:latest
          docker logout $DOCKER_REGISTRY
