# .github/workflows/ci-cd.yml
name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ feature ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest discover

      - name: Build and push Docker image
        if: github.ref == 'refs/heads/master' # Only build and push on main branch
        env:
          DOCKER_REGISTRY: docker.io
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
          IMAGE_NAME: ${{ env.DOCKER_USERNAME }}/your-repository-name
        run: |
          docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" $DOCKER_REGISTRY
          docker build -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:latest
          docker logout $DOCKER_REGISTRY
